Suggest `make clean` in Sanitizers tutorial
eecs280staff/tutorials pull request #179
Opened 2024-03-04 22:30 UTC by nskh

Adds a warning to run `make clean` after enabling sanitizers in Makefile to the Sanitizers tutorial

2024-03-05 14:10 UTC, awdeorio requested changes
Great idea!  I left a couple of suggestions.

2024-03-05 14:10 UTC, awdeorio commented on docs/setup_asan.md
> +**Note:** If you enable sanitizers in your `Makefile` and change nothing else in your code, you will need to do a `make clean` to recompile with the sanitizers on.
I'll also suggest moving this callout to the end of the subsection.

2024-03-05 15:27 UTC, jamesjuett commented on docs/setup_asan.md
> +**Note:** If you enable sanitizers in your `Makefile` and change nothing else in your code, you will need to do a `make clean` to recompile with the sanitizers on.
My 2 cents... the pitfall wording may be unclear to students as written. i.e. Is it a pitfall to do this? Or to forget to do it?

2024-03-05 15:48 UTC, nskh commented on docs/setup_asan.md
> +**Note:** If you enable sanitizers in your `Makefile` and change nothing else in your code, you will need to do a `make clean` to recompile with the sanitizers on.
I agree with James; we could say 
> To ensure your compiled code runs with sanitizers, remove and rebuild your executables after changing the `Makefile`. You can do this with `make clean`, for example.

It's a little more heavy-handed but is probably clearer for 280 students who may not know where to find, remove, and recompile executables.

2024-03-06 15:44 UTC, awdeorio commented on docs/setup_asan.md
> +**Note:** If you enable sanitizers in your `Makefile` and change nothing else in your code, you will need to do a `make clean` to recompile with the sanitizers on.
How about we go back to mostly the original text, including the label Pitfall to be consistent with other yellow callouts and including a `$ make clean` in a code block?  I'll revise my suggestion above.

2024-03-06 17:23 UTC, nskh commented on docs/setup_asan.md
> +**Note:** If you enable sanitizers in your `Makefile` and change nothing else in your code, you will need to do a `make clean` to recompile with the sanitizers on.
I like that a lot!

2024-03-07 12:51 UTC, awdeorio approved these changes
LGTM

2024-03-13 15:26 UTC, merged