CLI tutorial: first draft
eecs280staff/tutorials pull request #37
Opened 2022-11-20 07:28 UTC by ohjuny

[Issue #32](https://github.com/eecs280staff/tutorials/issues/32) raised the idea of a CLI tutorial that gives students context for other tutorials that use shell commands. This is a first draft based on the ideas in [this document](https://docs.google.com/document/d/1UiNLFpwRbENiScz5ESGkp4eXRDqOZC9ZX07WdHdmWh0) generated by Professor DeOrio and myself.

2022-11-30 01:06 UTC, awdeorio requested changes
This is a great start, @ohjuny !  I did a high-level initial pass and left some comments.  I realize that screenshots are tedious to redo, so feel free to workshop one of them to get it right before redoing others.

2022-11-30 01:06 UTC, awdeorio commented on docs/cli.md
> +<img src="images/cli003.png" width="768px" alt="ls cli example"/>
Try a screenshot with default light mode.  Then, add `class="invert-colors-in-dark-mode"`.  Give that a try with both light mode and dark mode. They should both look good.

2022-11-30 01:06 UTC, awdeorio commented on docs/cli.md
> +### .
```suggestion
### Current directory: `.`
```

You could apply this suggestion to the other special path subsection names

2022-11-30 01:06 UTC, awdeorio commented on docs/cli.md
> +<img src="images/cli018.png" width="768px" alt=".. example"/>
I'd use a `console` block here instead of a screenshot.  Same for the other "terminal only" screenshots.

2022-11-30 01:06 UTC, awdeorio commented on docs/cli.md
> +## open / wslview
TIL `wslview`!

2022-12-02 19:06 UTC, ohjuny commented on docs/cli.md
> +## open / wslview
yay :)

2022-12-06 21:06 UTC, closed without merging